### ISSUE TITLE
bad font rendering on literally every browser and device

### ISSUE THREAD

**Issue by marbelynrye** [SpiritAxolotl/spax.zone#49]
possible low quality font file

**Comment by CalmBubbles** [comment]
Got no problem with that, but
![IMG_20220325_134551](https://github.com/SpiritAxolotl/spax.zone/assets/100333110/d537e6f7-e9df-427a-b5c0-e01a8b573f10)
LMAO

**Comment by CalmBubbles** [comment]
Aight, opened the site on 2 desktops. Cause I usually view the site on mobile.

Font looks fine on mobile for some reason (for me).
But mushy/blurred on desktop.

Idk what method spax used for the font. But yeah, probably because of the thing u said.

The only hope of this being fixed, is if spax updates the fonts :v
Or if there's a `image-rendering: pixelated` counterpart for text

**Comment by SpiritAxolotl** [comment]
probably the outdated font-smoothing property but I can probably spend some time to add hinting or whatever to the font to optimize it

**Comment by SpiritAxolotl** [comment]
also, I used [this](https://www.pentacom.jp/pentacom/bitfontmaker2/) to get the basic shape of each character from the bitmap and for the ones that were taller than 16px I manually edited in FontForge
